import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import { ImageProvider } from "./context/ImageContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const merriweather = Merriweather({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

// export const metadata: Metadata = {
//   title: "",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: "Resources and Insights",
  description:
    "The latest industry news, interviews, technologies, and resources.",
  // icons: {
  //   icon: '/favicon.ico',
  // },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${merriweather.variable}`}>
        <ImageProvider>
          <main className="min-h-screen overflow-x-hidden">{children}</main>
        </ImageProvider>
      </body>
    </html>
  );
}
